name: Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
    
    - name: Create virtual environment
      run: python3 -m venv pred

    - name: Install dependencies
      run: ./pred/bin/pip install -r requirements.txt

    - name: Test environment
      run: ./pred/bin/python testEnvironment.py

    - name: Data Ingestion
      run: ./pred/bin/python src/pipeline/stage01_data_ingestion.py

    - name: Data Pre Processing
      run: ./pred/bin/python src/pipeline/stage02_data_processing.py

    - name: Model Training
      run: ./pred/bin/python src/pipeline/stage03_model_training.py

  post:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify success
      if: success()
      run: |
        echo "‚úÖ Training Pipeline completed successfully!"
        echo "üöÄ Triggering deployment job..."
        # Trigger another GitHub Action workflow if needed

    - name: Notify failure
      if: failure()
      run: echo "‚ùå Pipeline failed. Check logs."
